<?php

namespace AppBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRoles(){
        $q = $this->createQueryBuilder('r');
        $q->orderBy('r.name','ASC');
        $q->getQuery();
        return $q;
    }
}
