<?php

namespace AppBundle\Repository;

/**
 * UtenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtenteRepository extends \Doctrine\ORM\EntityRepository
{
}
