app:
    resource: "@AppBundle/Controller/"
    type:     annotation

accesso_negato:
    path: /accesso_negato
    defaults:
        _controller: FrameworkBundle:Template:template
        template: /default/forbidden.html.twig

logout:
    path: /logout