app:
    resource: "@AppBundle/Controller/"
    type:     annotation


udemy_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template: static/privacy.html.twig