app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#homepage_stringa:
#    path: /{nome}/{ruolo}
#    defaults: {_controller: AppBundle:Default:index}
#    methods: [GET,POST]
#    schemes: [https|http]
##    host: m.example.com
#    requirements:
#        nome: \D+

