app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#
#homepage_stringa:
#    path: /{_locale}/{nome}/{ruolo}.{_format}
#    defaults: {_controller: AppBundle:Default:index, ruolo: ADMIN,_format: html,title: "hello World"}
#    methods: [GET,POST]
#    schemes: [https|http]
##    host: m.example.com
#    requirements:
#        nome: "[a-z]{0,}"
#        _format: html|xml
#        _locale: '%app.locales%'

#app:
#    resource: "@AppBundle/Resources/config/rotte.yml"
#    prefix: /admin
