# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_denied_url: "/accesso_negato"

    encoders:
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        mio_provider:
            entity:
                class: AppBundle:User

        in_memory:
            memory:
                users:
                    alessio: { password: $2y$12$65xwQpdFwhA4PoTGs31FcOvZgoa3SzUjCUD.jrutERN4te1WP56dO, roles: ['ROLE_USER__']}
                    pippo2: { password: $2y$12$xDQa0ScZqd45WVFvpteL7e.PnT5fU217wkSF9F2R1DK4zZZfe52wy, roles: ['ROLE_ADMIN__']}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            switch_user: true
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout
                target: /

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED}
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY}
#        - { path: ^/admin, role: [ROLE_USER] }
